### ISSUE TITLE
ERROR in app: Exception on /api/listShells

### ISSUE THREAD

**Issue by Comanio00** [Mr-Un1k0d3r/ThunderShell#30]
Hi!
I installed ThunderShell, everything worked fine (console application and gui). After a few days of work, an error appears when I enter through the gui. I made a reinstall, the problem appeared again after several days of work.

ERROR in app: Exception on /api/listShells [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gnom13/tools/ThunderShell/core/webserver.py", line 149, in list_shells
    return render_template("shells.html", shells=app.get_shells(), uid=app.get_session_uid())
  File "/home/gnom13/tools/ThunderShell/core/webapi.py", line 211, in get_shells
    prompt = self.redis.get_prompt(shell.split(":")[0]).decode()
AttributeError: 'NoneType' object has no attribute 'decode'
[2019-04-01 09:00:58,857] ERROR in app: Exception on /api/listShells [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gnom13/tools/ThunderShell/core/webserver.py", line 149, in list_shells
    return render_template("shells.html", shells=app.get_shells(), uid=app.get_session_uid())
  File "/home/gnom13/tools/ThunderShell/core/webapi.py", line 211, in get_shells
    prompt = self.redis.get_prompt(shell.split(":")[0]).decode()
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by Mr-Un1k0d3r** [comment]
I will add a fix. This is most likely caused by a flush db command I don't know but it return a None instead of an empty set. I will add validation against the return value
