### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by comanio** [Mr-Un1k0d3r/ThunderShell#36]
Hi, I can not solve the problem, the error appears after entering the command and receiving a response.

![hell](https://user-images.githubusercontent.com/47736429/59488028-12e16000-8e87-11e9-993a-ae27e3bfa10d.png)

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dronlab/tools/ThunderShell/core/sync.py", line 66, in start_cmd_sync_thread
    guid = sync.get_cmd_output(guid)
  File "/home/dronlab/tools/ThunderShell/core/sync.py", line 38, in get_cmd_output
    data = b64decode(self.redis.get_data(item)).decode()
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by Mr-Un1k0d3r** [comment]
I will take a look at it I feel like there is an issue with the CLI versus the web interface. A tons of changes were made lately
.
