### ISSUE TITLE
TypeError in Kali

### ISSUE THREAD

**Issue by pasoles** [Mr-Un1k0d3r/ThunderShell#37]
Hi

In ubuntu works like a charm, in kali I get the following error:

```
Exception happened during processing of request from ('192.168.1.30', 53401)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/ThunderShell/core/httpd.py", line 37, in __init__
    self.rc4 = RC4(self.rc4_key)
  File "/opt/ThunderShell/core/rc4.py", line 12, in __init__
    self.rc4 = ARC4.new(key)
  File "/usr/local/lib/python3.7/dist-packages/Crypto/Cipher/ARC4.py", line 132, in new
    return ARC4Cipher(key, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Crypto/Cipher/ARC4.py", line 60, in __init__
    result = _raw_arc4_lib.ARC4_stream_init(c_uint8_ptr(key),
  File "/usr/local/lib/python3.7/dist-packages/Crypto/Util/_raw_api.py", line 145, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

Also in a clean kali install I get similar errors related to rc4 with an error` valueerror: _ARC4 key cannot be null`.

As I understand its a library dependency problem, any ideas??

P.S In latest default.json file the "}" at the end of file is missing

**Comment by Mr-Un1k0d3r** [comment]
We are making a lot of change to the code lately everything should be back to normal pretty soon sorry about that python 3 is a wild beast and 3.5 3.6 3.7 all act differently I'm trying to find a universal solution at the moment.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: pasoles <notifications@github.com> Date: 2019-07-12  07:07  (GMT-05:00) To: Mr-Un1k0d3r/ThunderShell <ThunderShell@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Mr-Un1k0d3r/ThunderShell] TypeError in Kali (#37) Hi
In ubuntu works like a charm, in kali I get the following error:
Exception happened during processing of request from ('192.168.1.30', 53401)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/ThunderShell/core/httpd.py", line 37, in __init__
    self.rc4 = RC4(self.rc4_key)
  File "/opt/ThunderShell/core/rc4.py", line 12, in __init__
    self.rc4 = ARC4.new(key)
  File "/usr/local/lib/python3.7/dist-packages/Crypto/Cipher/ARC4.py", line 132, in new
    return ARC4Cipher(key, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/Crypto/Cipher/ARC4.py", line 60, in __init__
    result = _raw_arc4_lib.ARC4_stream_init(c_uint8_ptr(key),
  File "/usr/local/lib/python3.7/dist-packages/Crypto/Util/_raw_api.py", line 145, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

Also in a clean kali install I get similar errors related to rc4 with an error valueerror: _ARC4 key cannot be null.
As I understand its a library dependency problem, any ideas??
P.S In latest default.json file the "}" at the end of file is missing

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Mr-Un1k0d3r/ThunderShell/issues/37?email_source=notifications\u0026email_token=ABAK3LTKAHBDL2IFETAPS2DP7BQWDA5CNFSM4ICHN2S2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G63JPLA",
"url": "https://github.com/Mr-Un1k0d3r/ThunderShell/issues/37?email_source=notifications\u0026email_token=ABAK3LTKAHBDL2IFETAPS2DP7BQWDA5CNFSM4ICHN2S2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G63JPLA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tothi** [comment]
fyi: https://github.com/Mr-Un1k0d3r/ThunderShell/pull/38

**Comment by tazz0** [comment]
Fixed by tothi https://github.com/Mr-Un1k0d3r/ThunderShell/pull/38
