### ISSUE TITLE
need help \windows\

### ISSUE THREAD

**Issue by riddickval** [Mr-Un1k0d3r/ThunderShell#42]
having issues running it...

C:\Windows\system32>C:\Windows\System32\ThunderShell-master\ThunderShell.py
Traceback (most recent call last):
  File "C:\Windows\System32\ThunderShell-master\ThunderShell.py", line 17, in <m
odule>
    from core.utils import Utils
  File "C:\Windows\System32\ThunderShell-master\core\utils.py", line 11, in <mod
ule>
    import ssl
  File "C:\Users\BEST\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 9
8, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.

C:\Windows\system32>

**Comment by Mr-Un1k0d3r** [comment]
your python installation was compiled without ssl you need to build it with the ssl option
